[build]
  command = "echo Building Functions"
  functions = "functions"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/interactions/*"
  status = 200
  to = "/.netlify/functions/interactions/:splat"